CREATE DATABASE QuanLyGiay	
use QuanLyGiay

CREATE TABLE LoaiGiay
(
	[MaLoai] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [TenGiay] NVARCHAR(200) NOT NULL, 
	[KichCo] INT NOT NULL, 
	[Loai]  NVARCHAR(200) NOT NULL,
)
Go

CREATE TABLE Giay
(
	[MaGiay] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [TenGiay] NVARCHAR(200) NOT NULL,
	[KichCo] INT NOT NULL,
	[Hang] NVARCHAR(200) NOT NULL,
)
Go
CREATE TABLE ThanhVien
(
	[MaTV] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [TenDN] NVARCHAR(200) NOT NULL,
	[MatKhau] NVARCHAR(200) NOT NULL
)
Go
/*--------------*/
ALTER TABLE Giay ADD CONSTRAINT FK_Sach_Loaigiay FOREIGN KEY (MaGiay) REFERENCES LoaiGiay(MaGiay) 

INSERT INTO LoaiGiay VALUES(N'Giày thể thao',42,N'Nike')
INSERT INTO LoaiGiay VALUES(N'Giày du lịch',41,N'Jordan')
INSERT INTO LoaiGiay VALUES(N'Giày đi làm',40,N'Boot')

/*Thêm dữ liệu mẫu*/
INSERT INTO Giay VALUES(N'Giày thể thao',42,N'Nike')
INSERT INTO Giay VALUES(N'Giày thể thao',39,N'Vans')
INSERT INTO Giay VALUES(N'Giày thể thao',36,N'Bitis')
INSERT INTO Giay VALUES(N'Giày thể thao',40,N'Adidas')
INSERT INTO Giay VALUES(N'Giày thể thao',45,N'Converse')
Go 

INSERT INTO ThanhVien VALUES(N'admin','7C4A8D09CA3762AF61E59520943DC26494F8941B')
INSERT INTO ThanhVien VALUES(N'thanhvien1','7C4A8D09CA3762AF61E59520943DC26494F8941B')
INSERT INTO ThanhVien VALUES(N'thanhvien2','7C4A8D09CA3762AF61E59520943DC26494F8941B')
GO
/*DROP DATABASE QuanLyGiay;
/*DELETE FROM Sach;
//
